# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trade.ui'
#
# Created: Sat Oct 28 17:20:56 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 621)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 151, 231))
        self.groupBox.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 10pt \"Cambria\";")
        self.groupBox.setObjectName("groupBox")
        self.radio_trend = QtGui.QRadioButton(self.groupBox)
        self.radio_trend.setGeometry(QtCore.QRect(20, 30, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.radio_trend.setFont(font)
        self.radio_trend.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.radio_trend.setObjectName("radio_trend")
        self.radio_bollinger = QtGui.QRadioButton(self.groupBox)
        self.radio_bollinger.setGeometry(QtCore.QRect(20, 60, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.radio_bollinger.setFont(font)
        self.radio_bollinger.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.radio_bollinger.setObjectName("radio_bollinger")
        self.radio_rsi = QtGui.QRadioButton(self.groupBox)
        self.radio_rsi.setGeometry(QtCore.QRect(20, 120, 82, 17))
        self.radio_rsi.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.radio_rsi.setObjectName("radio_rsi")
        self.radio_cci = QtGui.QRadioButton(self.groupBox)
        self.radio_cci.setGeometry(QtCore.QRect(20, 90, 82, 17))
        self.radio_cci.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.radio_cci.setObjectName("radio_cci")
        self.checkbox_volume = QtGui.QCheckBox(self.groupBox)
        self.checkbox_volume.setGeometry(QtCore.QRect(20, 150, 70, 17))
        self.checkbox_volume.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.checkbox_volume.setObjectName("checkbox_volume")
        self.txt_volume = QtGui.QLineEdit(self.groupBox)
        self.txt_volume.setGeometry(QtCore.QRect(100, 150, 41, 20))
        self.txt_volume.setObjectName("txt_volume")
        self.btn_fill_volume = QtGui.QPushButton(self.groupBox)
        self.btn_fill_volume.setGeometry(QtCore.QRect(10, 190, 61, 31))
        self.btn_fill_volume.setStyleSheet("color:rgb(85, 0, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.btn_fill_volume.setObjectName("btn_fill_volume")
        self.btn_fill_volume_2 = QtGui.QPushButton(self.groupBox)
        self.btn_fill_volume_2.setGeometry(QtCore.QRect(90, 190, 51, 31))
        self.btn_fill_volume_2.setStyleSheet("color:rgb(85, 0, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.btn_fill_volume_2.setObjectName("btn_fill_volume_2")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 20, 151, 231))
        self.groupBox_2.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 10pt \"Cambria\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.list_top_five = QtGui.QListWidget(self.groupBox_2)
        self.list_top_five.setGeometry(QtCore.QRect(10, 21, 131, 191))
        self.list_top_five.setObjectName("list_top_five")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 20, 201, 231))
        self.groupBox_3.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 9pt \"Cambria\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 41, 91))
        self.pushButton.setStyleSheet("color:rgb(0, 170, 0)")
        self.pushButton.setObjectName("pushButton")
        self.label_name_coin_imidiete = QtGui.QLabel(self.groupBox_3)
        self.label_name_coin_imidiete.setGeometry(QtCore.QRect(100, 10, 61, 16))
        self.label_name_coin_imidiete.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_name_coin_imidiete.setObjectName("label_name_coin_imidiete")
        self.btn_sell_imi = QtGui.QPushButton(self.groupBox_3)
        self.btn_sell_imi.setGeometry(QtCore.QRect(10, 130, 41, 91))
        self.btn_sell_imi.setStyleSheet("color:rgb(255, 0, 0)")
        self.btn_sell_imi.setObjectName("btn_sell_imi")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(60, 30, 111, 51))
        self.groupBox_4.setStyleSheet("color:rgb(0, 0, 255)")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.radio_percent_buy_imi = QtGui.QRadioButton(self.groupBox_4)
        self.radio_percent_buy_imi.setGeometry(QtCore.QRect(10, 10, 82, 17))
        self.radio_percent_buy_imi.setObjectName("radio_percent_buy_imi")
        self.radio_quantity_buy_imi = QtGui.QRadioButton(self.groupBox_4)
        self.radio_quantity_buy_imi.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radio_quantity_buy_imi.setObjectName("radio_quantity_buy_imi")
        self.txt_buy_imi = QtGui.QLineEdit(self.groupBox_3)
        self.txt_buy_imi.setGeometry(QtCore.QRect(60, 90, 81, 31))
        self.txt_buy_imi.setStyleSheet("color:rgb(0, 0, 255)")
        self.txt_buy_imi.setObjectName("txt_buy_imi")
        self.txt_sell_imi = QtGui.QLineEdit(self.groupBox_3)
        self.txt_sell_imi.setGeometry(QtCore.QRect(60, 190, 81, 31))
        self.txt_sell_imi.setStyleSheet("color:rgb(0, 0, 255)")
        self.txt_sell_imi.setObjectName("txt_sell_imi")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(60, 130, 111, 51))
        self.groupBox_5.setStyleSheet("color:rgb(0, 0, 255)")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.radio_percent_sell_imi = QtGui.QRadioButton(self.groupBox_5)
        self.radio_percent_sell_imi.setGeometry(QtCore.QRect(10, 10, 82, 17))
        self.radio_percent_sell_imi.setObjectName("radio_percent_sell_imi")
        self.radio_quantity_sell_imi = QtGui.QRadioButton(self.groupBox_5)
        self.radio_quantity_sell_imi.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radio_quantity_sell_imi.setObjectName("radio_quantity_sell_imi")
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(600, 270, 271, 291))
        self.groupBox_6.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 10pt \"Cambria\";")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_2 = QtGui.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 31, 16))
        self.label_2.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.label_2.setObjectName("label_2")
        self.label_balance_btc = QtGui.QLabel(self.groupBox_6)
        self.label_balance_btc.setGeometry(QtCore.QRect(70, 20, 71, 16))
        self.label_balance_btc.setStyleSheet("color: rgb(0,0, 0);\n"
"font: 75 10pt \"Cambria\";")
        self.label_balance_btc.setObjectName("label_balance_btc")
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(160, 20, 31, 16))
        self.label_4.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.label_4.setObjectName("label_4")
        self.label_balance_usd = QtGui.QLabel(self.groupBox_6)
        self.label_balance_usd.setGeometry(QtCore.QRect(190, 20, 71, 16))
        self.label_balance_usd.setStyleSheet("color: rgb(0,0, 0);\n"
"font: 75 10pt \"Cambria\";")
        self.label_balance_usd.setObjectName("label_balance_usd")
        self.btn_update_balance = QtGui.QPushButton(self.groupBox_6)
        self.btn_update_balance.setGeometry(QtCore.QRect(150, 260, 81, 23))
        self.btn_update_balance.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.btn_update_balance.setObjectName("btn_update_balance")
        self.list_balance = QtGui.QListWidget(self.groupBox_6)
        self.list_balance.setGeometry(QtCore.QRect(10, 40, 241, 211))
        self.list_balance.setObjectName("list_balance")
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 270, 251, 291))
        self.groupBox_7.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 10pt \"Cambria\";")
        self.groupBox_7.setObjectName("groupBox_7")
        self.btn_update_coin_current = QtGui.QPushButton(self.groupBox_7)
        self.btn_update_coin_current.setGeometry(QtCore.QRect(150, 260, 81, 23))
        self.btn_update_coin_current.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.btn_update_coin_current.setObjectName("btn_update_coin_current")
        self.btn_cancel = QtGui.QPushButton(self.groupBox_7)
        self.btn_cancel.setGeometry(QtCore.QRect(20, 260, 81, 23))
        self.btn_cancel.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.btn_cancel.setObjectName("btn_cancel")
        self.list_coin_current = QtGui.QListWidget(self.groupBox_7)
        self.list_coin_current.setGeometry(QtCore.QRect(10, 30, 221, 221))
        self.list_coin_current.setObjectName("list_coin_current")
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(280, 270, 311, 291))
        self.groupBox_8.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 10pt \"Cambria\";")
        self.groupBox_8.setObjectName("groupBox_8")
        self.btn_update_coin_history = QtGui.QPushButton(self.groupBox_8)
        self.btn_update_coin_history.setGeometry(QtCore.QRect(210, 260, 81, 23))
        self.btn_update_coin_history.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 10pt \"Cambria\";")
        self.btn_update_coin_history.setObjectName("btn_update_coin_history")
        self.list_coin_history = QtGui.QListWidget(self.groupBox_8)
        self.list_coin_history.setGeometry(QtCore.QRect(20, 30, 271, 221))
        self.list_coin_history.setObjectName("list_coin_history")
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(550, 20, 321, 231))
        self.groupBox_9.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 9pt \"Cambria\";")
        self.groupBox_9.setObjectName("groupBox_9")
        self.btn_buy_profit = QtGui.QPushButton(self.groupBox_9)
        self.btn_buy_profit.setGeometry(QtCore.QRect(10, 30, 41, 91))
        self.btn_buy_profit.setStyleSheet("color:rgb(0, 170, 0)")
        self.btn_buy_profit.setObjectName("btn_buy_profit")
        self.label_name_coin_profit = QtGui.QLabel(self.groupBox_9)
        self.label_name_coin_profit.setGeometry(QtCore.QRect(140, 10, 61, 16))
        self.label_name_coin_profit.setStyleSheet("color:rgb(0, 0, 255)")
        self.label_name_coin_profit.setObjectName("label_name_coin_profit")
        self.btn_sell_profit = QtGui.QPushButton(self.groupBox_9)
        self.btn_sell_profit.setGeometry(QtCore.QRect(10, 130, 41, 91))
        self.btn_sell_profit.setStyleSheet("color:rgb(255, 0, 0)")
        self.btn_sell_profit.setObjectName("btn_sell_profit")
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_10.setGeometry(QtCore.QRect(60, 30, 91, 51))
        self.groupBox_10.setStyleSheet("color:rgb(0, 0, 255)")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.radio_percent_buy_profit = QtGui.QRadioButton(self.groupBox_10)
        self.radio_percent_buy_profit.setGeometry(QtCore.QRect(10, 10, 82, 17))
        self.radio_percent_buy_profit.setStyleSheet("color:rgb(0, 0, 255)")
        self.radio_percent_buy_profit.setObjectName("radio_percent_buy_profit")
        self.radio_quantity_buy_profit = QtGui.QRadioButton(self.groupBox_10)
        self.radio_quantity_buy_profit.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radio_quantity_buy_profit.setObjectName("radio_quantity_buy_profit")
        self.txt_buy_1_profit = QtGui.QLineEdit(self.groupBox_9)
        self.txt_buy_1_profit.setGeometry(QtCore.QRect(60, 90, 61, 31))
        self.txt_buy_1_profit.setObjectName("txt_buy_1_profit")
        self.txt_sell_1_profit = QtGui.QLineEdit(self.groupBox_9)
        self.txt_sell_1_profit.setGeometry(QtCore.QRect(60, 190, 61, 31))
        self.txt_sell_1_profit.setObjectName("txt_sell_1_profit")
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_11.setGeometry(QtCore.QRect(60, 130, 91, 51))
        self.groupBox_11.setStyleSheet("color:rgb(0, 0, 255)")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.radio_percent_sell_profit = QtGui.QRadioButton(self.groupBox_11)
        self.radio_percent_sell_profit.setGeometry(QtCore.QRect(10, 10, 82, 17))
        self.radio_percent_sell_profit.setObjectName("radio_percent_sell_profit")
        self.radio_quantity_sell_profit = QtGui.QRadioButton(self.groupBox_11)
        self.radio_quantity_sell_profit.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radio_quantity_sell_profit.setObjectName("radio_quantity_sell_profit")
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_12.setGeometry(QtCore.QRect(180, 30, 131, 51))
        self.groupBox_12.setStyleSheet("color:rgb(0, 0, 255)")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.radio_percent_ask_buy_profit = QtGui.QRadioButton(self.groupBox_12)
        self.radio_percent_ask_buy_profit.setGeometry(QtCore.QRect(10, 10, 82, 17))
        self.radio_percent_ask_buy_profit.setObjectName("radio_percent_ask_buy_profit")
        self.radio_ask_buy_profit = QtGui.QRadioButton(self.groupBox_12)
        self.radio_ask_buy_profit.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radio_ask_buy_profit.setObjectName("radio_ask_buy_profit")
        self.txt_buy_2_profit = QtGui.QLineEdit(self.groupBox_9)
        self.txt_buy_2_profit.setGeometry(QtCore.QRect(180, 90, 101, 31))
        self.txt_buy_2_profit.setObjectName("txt_buy_2_profit")
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_13.setGeometry(QtCore.QRect(180, 130, 131, 51))
        self.groupBox_13.setStyleSheet("color:rgb(0, 0, 255)")
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.radio_percent_bid_sell = QtGui.QRadioButton(self.groupBox_13)
        self.radio_percent_bid_sell.setGeometry(QtCore.QRect(10, 10, 82, 17))
        self.radio_percent_bid_sell.setObjectName("radio_percent_bid_sell")
        self.radio_bid_sell = QtGui.QRadioButton(self.groupBox_13)
        self.radio_bid_sell.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radio_bid_sell.setObjectName("radio_bid_sell")
        self.txt_sell_2_profit = QtGui.QLineEdit(self.groupBox_9)
        self.txt_sell_2_profit.setGeometry(QtCore.QRect(180, 190, 101, 31))
        self.txt_sell_2_profit.setObjectName("txt_sell_2_profit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PROGRAME EXCHANGE", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "STRAGERY", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_trend.setText(QtGui.QApplication.translate("MainWindow", "TREND", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_bollinger.setText(QtGui.QApplication.translate("MainWindow", "BOLLINGERBAND", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_rsi.setText(QtGui.QApplication.translate("MainWindow", "RSI", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_cci.setText(QtGui.QApplication.translate("MainWindow", "CCI", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_volume.setText(QtGui.QApplication.translate("MainWindow", "VOLUME", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fill_volume.setText(QtGui.QApplication.translate("MainWindow", "FILL", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fill_volume_2.setText(QtGui.QApplication.translate("MainWindow", "LOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "TOP FIVE", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "BUY-SELL IMIDIETE", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "BUY", None, QtGui.QApplication.UnicodeUTF8))
        self.label_name_coin_imidiete.setText(QtGui.QApplication.translate("MainWindow", "BTC-ARK", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sell_imi.setText(QtGui.QApplication.translate("MainWindow", "SELL", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_percent_buy_imi.setText(QtGui.QApplication.translate("MainWindow", "percent", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_quantity_buy_imi.setText(QtGui.QApplication.translate("MainWindow", "quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_percent_sell_imi.setText(QtGui.QApplication.translate("MainWindow", "percent", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_quantity_sell_imi.setText(QtGui.QApplication.translate("MainWindow", "quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "BALANCE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "BTC :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_balance_btc.setText(QtGui.QApplication.translate("MainWindow", "0.01296", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "USD:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_balance_usd.setText(QtGui.QApplication.translate("MainWindow", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_update_balance.setText(QtGui.QApplication.translate("MainWindow", "update", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "COIN CURRENT EXCHANGE", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_update_coin_current.setText(QtGui.QApplication.translate("MainWindow", "update", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("MainWindow", "cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "HISTORY EXCHANGE", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_update_coin_history.setText(QtGui.QApplication.translate("MainWindow", "update", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "BUY-SELL BY PROFIT", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_buy_profit.setText(QtGui.QApplication.translate("MainWindow", "BUY", None, QtGui.QApplication.UnicodeUTF8))
        self.label_name_coin_profit.setText(QtGui.QApplication.translate("MainWindow", "BTC-ARK", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sell_profit.setText(QtGui.QApplication.translate("MainWindow", "SELL", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_percent_buy_profit.setText(QtGui.QApplication.translate("MainWindow", "percent", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_quantity_buy_profit.setText(QtGui.QApplication.translate("MainWindow", "quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_percent_sell_profit.setText(QtGui.QApplication.translate("MainWindow", "percent", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_quantity_sell_profit.setText(QtGui.QApplication.translate("MainWindow", "quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_percent_ask_buy_profit.setText(QtGui.QApplication.translate("MainWindow", "percent ask", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_ask_buy_profit.setText(QtGui.QApplication.translate("MainWindow", "ask", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_percent_bid_sell.setText(QtGui.QApplication.translate("MainWindow", "percent bid", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_bid_sell.setText(QtGui.QApplication.translate("MainWindow", "bid", None, QtGui.QApplication.UnicodeUTF8))

